// user profile
export const PROFILE_ME = 'PROFILE_ME';

// material
export const MATERIAL_FETCHING = 'MATERIAL_FETCHING';
export const MATERIAL_FETCHING_SUCCESS = 'MATERIAL_FETCHING_SUCCESS';

export const MATERIAL_USER_REACTION_REQUESTING = 'MATERIAL_USER_REACTION_REQUESTING';
export const MATERIAL_USER_REACTION_SUCCESS = 'MATERIAL_USER_REACTION_SUCCESS';
